# Generated by Django 3.2.17 on 2023-02-09 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20230209_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(default='Alpine-Ski', max_length=255),
        ),
    ]
